disabled_rules: # rule identifiers to exclude from running
  #- colon
  #- comma
  #- control_statement
  - line_length
  - trailing_whitespace
  - legacy_constructor

force_cast: warning

excluded:
  - Carthage
  - Pods

variable_name:
  excluded:
    - ObisoftUserId
    - GU_RelationId
    - ObisoftUsr
    - GU_Relations
    - TU_Relations
    - EU_Relations

type_name:
  excluded:
    - GU_RelationR
