platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 3.3.0'
pod 'KeychainSwift', '~> 3.0.11'
pod 'SDWebImage', '~> 3.7.5'
pod 'FontAwesome.swift', '~> 0.7.1'
pod 'AsyncSwift', '~> 1.7.2'
pod 'Alamofire-Synchronous', '~> 3.0.0'
pod 'PinYin4Objc', '~> 1.1.1'
